### ISSUE TITLE
Issues in lab

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#1]
# Lab/Demo: 3.2
#### Steps: 2 - 3
**Click **Add Existing** and select **Entity**.
Select the **Feedback** and **User** entities and click **Next**.**

It should be mentioned that these two existing entities must be added individually (repeat steps 3 and 4 for each entity).

# Lab/Demo: 4.2
#### Step: 10
**In the **Field Explorer** (the left bar showing the fields), uncheck the **Show only unused fields** checkbox.**

Field Explorer is now called Table Columns

# Lab/Demo: 4.3
#### Step: 5
**You will add the Created On field back to the view. Click on the **+ Add Column**
button located on the top right of the view.**

There is no **+ Add Column** button  - instead only a **+ View Column** button.

# Lab/Demo: 4.6 
#### Step: 45
**Set the **OnCheck** property to the snippet below. This snippet will add the points of the check answer to the Collection.
                Collect(UserAnswers, {Question:GUID(ThisItem.'Knowledge Question'), Points:ThisItem.'Answer 4 Points'})**

'onCheck' action provides the below error.
![2021-01-18_182150](https://user-images.githubusercontent.com/62302805/104970598-0eadea80-59ba-11eb-9d24-9e86650638f0.JPG)

# Lab/Demo: 4.8
#### Steps: 11-12
**11. Add the snippet below to the content you currently have. This snippet willadd a function that will set the **ShowResults** value to **true**.
            ;UpdateContext({ShowResults:true})**

The semicolon in the paste-able text provided should be removed else it achieves the following;
![2021-01-18_182839](https://user-images.githubusercontent.com/62302805/104970877-01453000-59bb-11eb-9d0c-2e3a8c673eba.JPG)

12. Due to this issue outlined in Lab 4.6, the following steps will be performed on 'Answer3Selected'

# Lab/Demo: 4.8
#### Step: 13
**13. Select the **resultsScreen** and navigate to the **Insert** tab. Add the **Left** icon to the upper left corner. Change the color to **white.****

'UserResultList' should be resized before this step.

# Lab/Demo: 4.8
#### Step: 6
**6.  Select the **OnSelect** property of the icon and provide the function below.
    This function will run when the icon is clicked and navigate to the Results
    Screen.
            Refresh(Users);Navigate(resultsScreen, ScreenTransition.None)**

Users should be Prompted to "**save their work**" here.

# Lab/Demo: 4.8
#### Step: 18
 **18. Click **Submit Feedback**.**
Status reason is required in the feedback, giving the below error:
![2021-01-18_183805](https://user-images.githubusercontent.com/62302805/104971299-5f264780-59bc-11eb-96b6-c5d0129e1a8c.JPG)

# Lab/Demo: 5.1
#### Step: 12-13
**12. Click **Next**.**
**13. Uncheck the **Send Password in Email** checkbox.**

These steps should be reversed. You uncheck send password in email BEFORE you click next. 

# Lab/Demo: 5.3
#### Step: 10
 **Go to the **Rule** section, select **Question Type** for **Field**, select
    **Equals** for **Operator**, select **Value** for **Type**, and select
    **Scenario** for **Value**.**

""Type** is not an available field; This is due to the 'Question Type' Column having the type 'Questions' instead of 'Question'. The appropriate change has been made in task 1 and 2 of this lab.
![2021-01-18_190117](https://user-images.githubusercontent.com/62302805/104972353-90544700-59bf-11eb-8b0d-e8aa28e1e3b0.JPG)

# Lab/Demo: 5.4
#### Step: 10
**On the Set Question Points popup, click + Add Action.**

User must enable pop ups for this step to follow.

# Lab/Demo: 5.4
#### Step:3
**Select **Assessments** and click to open the **Test Assessment Four**.** 

The user should navigate to **'Knowledge Assessments'** not 'Assessments'

# Lab/Demo: 5.5
#### Step: 6
The flow creation menu has changed - see below;
![2021-01-18_191249](https://user-images.githubusercontent.com/62302805/104972925-2e94dc80-59c1-11eb-94ed-acf25c148a9e.JPG)

# Lab/Demo: 5.5 
#### Step: 4 
The user should navigate to **'Knowledge Assessments'** not 'Assessments'

# Lab/Demo: 5.5
#### Step: 9
**Select Using Data from Previous Runs.**

No previous data available
![2021-01-18_191632](https://user-images.githubusercontent.com/62302805/104973079-b4b12300-59c1-11eb-9ef2-5540cafd12c2.JPG)
 

# Lab/Demo: 5.6
#### Step: 3 
The flow creation menu has changed - see below:
![image](https://user-images.githubusercontent.com/62302805/104973158-e4f8c180-59c1-11eb-8fb2-15188b7cd096.png)

# Lab/Demo: 5.8
#### Step: 35
The business rule created locks the status field once approved - not unlock it. 

![2021-01-18_192336](https://user-images.githubusercontent.com/62302805/104973432-add6e000-59c2-11eb-90a4-cde7c23d6ff4.JPG)

**Comment by anjenni** [comment]
Thanks so much for logging these issues, this is extremely helpful! We are retesting and will fix these in the next few days. Unfortunately some of the UI changes due to the Dataverse terminology changes are still showing up in the UI, so some of the terminology may be confusing for the time being - we will keep updating those as they come. I'll close out this issue when all the bugs we can fix are completed.

Thanks again!

**Comment by hope77777** [comment]
Hi, Just checking on these issues. Is there a time frame on implementation?

**Comment by chandlersyal** [comment]
These should all be addressed with the latest update (October). Thank you!
