### ISSUE TITLE
Removed property or some step by step instructions do not fit the designer   

### ISSUE THREAD

**Issue by TheMaty** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#11]
# Module: 4
#### Step: 12

Description of issue

Task 4 - Add Feedback Screen 

( https://microsoftlearning.github.io/PL-200-Power-Platform-Functional-Consultant/Instructions/Labs/LAB%5BPL-200%5D_M04L07_Work_with_data.html )

Step 12:
Select the Title field. In the Advanced pane, select unlock. Expand More options in the Data section.

Issue :
I can not see "more Options" to expand in the Data Section. 

# Module: 4
#### Step: 19

Step 19 :
With the submitFeedbackButton still selected, return to the Properties tab and select the DisplayMode property.

Step 20:
Replace the DisplayMode property value with snippet below. This snippet will enable the button if the comments filed has value and disable it if the comments field is blank.

Issue:
submitFeedbackButton > Properties > Display mode is combobox with
-Disabled
-Edit
-View
values.
so, It is not allowed to set scripting of following;
 If(IsBlank(userCommentsText), DisplayMode.Disabled, DisplayMode.Edit)
to the field

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
Step 12 - the UI has updated and you no longer need to click "More options" to see the Default property in the Data section. Will remove this line to avoid confusion.
Step 20 - you add this script in the function bar at the top. 
![image](https://user-images.githubusercontent.com/66968984/131385867-03fef507-fe96-4d5b-ac72-b4b8e35784ae.png)
