### ISSUE TITLE
Move setup of Power Pages

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#158]
# Module: 1
### Exercise 2 Sign up for Power Pages
Description of issue

Need to move the setup of Power Pages from Lab 1.1 to Lab 0 or to the end of 1.3 as the installation of the portal solutions (which can take 45-60 minutes) causes timeouts in Labs 1.2 and 1.3

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.
