### ISSUE TITLE
import issue in Fabrikam Environmental

### ISSUE THREAD

**Issue by prithvirajs** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#159]
# Module: 04
#### Step: 07

Description of issue
You'll need to import the following items to this environment in order to import Fabrikam Environmental

Missing Dependencies
Alert Subscription
adx_alertsubscription
Table
Environmental Work Delivery
Canvas app

Repro steps:

1.Export solution
1.import solution
1.
![image](https://user-images.githubusercontent.com/18575014/204269217-d662111d-143c-4ff3-9979-615095ed7f1b.png)
![image](https://user-images.githubusercontent.com/18575014/204269272-583aa9f0-d4a4-4a7e-87a5-4f4b7c2e4d77.png)

**Comment by chaast** [comment]
i had the same with two students as well last week (myself and the other 8 had no issues). after waiting a few minutes and trying again it was ok for them.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by bpmoring** [comment]
Adding to list of things to watch for. Closing for now.
