### ISSUE TITLE
Typing error in lab 6.2 - business process flow stages

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#160]
# Module: 6
#### Step: 16

Description of issue:
The lab instructs you to go to the "resolve stage", however it should say "rejected stage" for the exercise to be completed correctly.

**Comment by julians1966** [comment]
Pull request 166 https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/pull/166 fixes this

**Comment by bpmoring** [comment]
Corrected in recent updates.
