### ISSUE TITLE
Practice Lab 0 - Validate lab environment - Exercise 2 – Sign up for Power Pages - XX Practice Environment not yet created

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#167]
The XX Practice environment is only created in Lab 1.1. In Lab 0, Exercise 2 you ask the student to 

Practice Lab 0 - Validate lab environment
Exercise 2 – Sign up for Power Pages
In this exercise, you will provision a Power Pages site. This can take a while, so you will follow these steps to start the provisioning process in the background while you progress through your labs. You will configure the site in a future lab.

Task 1.1 - Create a Power Pages site
Step 1. Navigate to the Power Pages portal https://make.powerpages.microsoft.com/ and sign in with your Microsoft 365 credentials if prompted.

Step 2. Use the Environment selector to switch to your **Practice** environment.

The student practice environment is not created until Lab 1.1.  

![image](https://user-images.githubusercontent.com/1082625/218549843-f1368b1f-7471-440d-9c7f-d871528bfa6f.png)

WORKAROUND

Simply create the PRACTICE environment in Lab 1.1 and then come back and do Lab 0 Ex 2 Create Power Pages site. Then continue on with Lab 1.1 where you had stopped after the PRACTICE environment was created.

**Comment by bpmoring** [comment]
Update made with latest PR.
