### ISSUE TITLE
Lab 1.3 - Ex 1 - Task 1 - Fabrikam imports with warnings. Then says import was successful. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#168]
Exercise 1 - Import Fabrikam solutions
In this exercise, you will import the main solution into the Practice environment.

Task 1.1 – Main solution

Step 11: Click Import.

The solution will import in the background. This may take a few minutes. Wait until the import has completed. 
----------------
This is the Warning error message: 

Solution "Fabrikam Environmental" imported successfully with warnings: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'dace5e42-212d-ed11-9db1-0022481dae3d' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

-------------------------

After I clicked on the X for the Warning message the next message was that the Frabrikam import was successful. 

Workaround: 

I am not sure how this is going to impact future labs. I deleted the Frabrikam solution and reimported it. This time a different Warning message was presented in that it said it activated and replaced the workflows associated with the solution. 

At this stage, I am continuing with the labs. 

I have also raised the issue with LODS Skillable. 

![image](https://user-images.githubusercontent.com/1082625/218850028-078ba07f-b607-4937-b36b-88f9f4d97430.png)

[Fabrikam Environmental_import.txt](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/files/10736438/Fabrikam.Environmental_import.txt)

1.
1.
1.

**Comment by julians1966** [comment]
I have replicated this warning.

**Comment by arnoldvilleneuve** [comment]
I could not see anything wrong with the solution and the rest of the week went ok. 

It's just a rather disconcerting message and I would like to be able to explain it to students.

**Comment by julians1966** [comment]
To resolve the issue, just Turn on the Daily status changes flow

**Comment by bpmoring** [comment]
Update made with latest PR.
