### ISSUE TITLE
Practice Lab 1.6 – Relationships - Ex 1 - Task 1.2 - No Milestone relationship in the Project table that's obvious to students.

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#170]
# Module: 1
#### Step: 1

Description of issue
There is NO Milestone relationship in the Project table. 

![image](https://user-images.githubusercontent.com/1082625/218876422-67656c47-a7d2-4fad-a57b-b9622bfe4af5.png)

There is a Project relationship in the Milestone table. 
![image](https://user-images.githubusercontent.com/1082625/218876635-3fe69a41-03e5-4e64-9add-e4763eaa5cb3.png)

----------------------

Is Step 1 backwards? 

Or should the Project table have a Milestone relationship? 

All students ran into the same issue in Lab 1.6. I see what you are saying in the step but it stumped them all. Please reword and include a screenshot. 

SOLUTION
The step is poorly worded and could use a screenshot or two. 

![image](https://user-images.githubusercontent.com/1082625/218879404-9dddadf7-da12-4328-88ee-bcc28d30195b.png)

![image](https://user-images.githubusercontent.com/1082625/218879560-f03757d3-9afb-4717-9d3a-d4a9ec129752.png)

This is a very good example of where a couple of screenshots go a long way. Some students tend to move ahead in labs and as such are going to run into issues like this on their own. Some people are actually doing their labs at night because they have to attend the course and keep up with work. We should make it easier for them for when they are working on their own. 

Thank you. 

UPDATE: Rest of the lab worked well as of today. Frabrikam imported successfully.

**Comment by bpmoring** [comment]
Updated with clarifying verbiage.
