### ISSUE TITLE
Practice Lab 1.3 - Import solution

### ISSUE THREAD

**Issue by Chlngu** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#171]
# Module: Pl 200 
#### Step: 00

Description of issue

Hi I tried to import this file (FabrikamChatbot_1_1_1_1.zip) to my PA platform but I got an error. 
Any Idea why?

![image](https://user-images.githubusercontent.com/125465626/219029190-b1a49ed5-6064-4988-8e0b-676443f8ba63.png)

**Comment by arnoldvilleneuve** [comment]
This worked ok for us on the first day. 

We did have some student imports fail but when we tried it again it worked! So far I have completed the labs for Day 2 and part of day 3 with only minor issues. The lab instructions could use improvement and in particular, screenshots should be provided even if we acknowledge that the UI changes. Students with no or little Power Platform experience will struggle, especially if they are trying to complete the labs on their own without an Instructor to assist them.

**Comment by Chlngu** [comment]
Ok so you suggest me to try to import it a few more times ? @arnoldvilleneuve ?

**Comment by arnoldvilleneuve** [comment]
Just once. Or create a new environment and start over. Get Outlook for Android

**Comment by adnkai** [comment]
This is still an issue. I tried to import 4-5 times. I'm getting the following error:

**Error**
```
{"statuscode":500,"statusdescription":"Internal Server
            Error","errors":[{"code":10000,"message":"One or more errors occurred."}]}
```
**Full error**
```
<Row ss:AutoFitHeight="0" type="Solution">
    <Cell ss:StyleID="s137" name="Time">
        <Data ss:Type="String">07:43:19.67</Data>
    </Cell>
    <Cell ss:StyleID="s137" name="ItemType">
        <Data ss:Type="String">Solution</Data>
    </Cell>
    <Cell ss:StyleID="s137" name="Id">
        <Data ss:Type="String"></Data>
    </Cell>
    <Cell ss:StyleID="s137" name="Name">
        <Data ss:Type="String">FabrikamChatbot</Data>
    </Cell>
    <Cell ss:StyleID="s137" name="LocalizedName">
        <Data ss:Type="String">Fabrikam Chatbot</Data>
    </Cell>
    <Cell ss:StyleID="s137" name="OriginalName">
        <Data ss:Type="String"></Data>
    </Cell>
    <Cell ss:StyleID="s137" name="Description">
        <Data ss:Type="String"></Data>
    </Cell>
    <Cell ss:StyleID="s137" name="Status">
        <Data ss:Type="String">Failure</Data>
    </Cell>
    <Cell ss:StyleID="s137" name="ErrorCode">
        <Data ss:Type="String"></Data>
    </Cell>
    <Cell ss:StyleID="s137" name="ErrorText">
        <Data ss:Type="String">Import failed:
            {"statuscode":500,"statusdescription":"Internal Server
            Error","errors":[{"code":10000,"message":"One or more errors occurred."}]}</Data>
    </Cell>
</Row>
```
