### ISSUE TITLE
Practice Lab 2.2 - Import data - Ex1 - Task 1.1

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#173]
Practice Lab 2.2 - Import data - Ex1 - Task 1.1

Description of issue

Edge browser does not have access to local storage.  

Solution

This seems to be a common problem with Edge and Azure / SharePoint / Onedrive. It is a problem with the Edge browser settings. 

Only one of six users encountered this issue. 

1. Go to Microsoft Edge Browser Settings. 

![image](https://user-images.githubusercontent.com/1082625/219125379-4eef09ec-58a5-4fa7-98ef-fd938591c91d.png)

Turn off the "Set Tracking prevention".

That seemed to work. Your mileage may vary.

**Comment by bpmoring** [comment]
Thank you for this information. We will look into this issue when we update the VM.
