### ISSUE TITLE
Practice Lab 3.1 – Forms

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#174]
Task 1.2 – Add Timeline control to main form

Step 11 - Check the Hide label box. 
Note Text of the Timeline section generates "unexpected error occurred" 
![image](https://user-images.githubusercontent.com/1082625/219210689-cce01938-b5ba-4e36-8ce6-28f32db5840f.png)

Step 13 - In the properties pane on the right-hand side, click on Fax, uncheck the Enable box, and click Done.
Step 14 - In the properties pane on the right-hand side, click on Letter, uncheck the Enable box, and click Done.

*** The Enable boxes are already unchecked. 
====================
Task 9.1 – Copy Outcome form

Step 9 - In the properties pane on the right-hand side, enter User for Display Name
Note: You are renaming the Display Name from Information to User. 
Step 35 - Drag Manager above Information.
Note: Information was renamed to User so you have to drag Manager above User and not Information. 
==================
Task 10.1 – Environmental Management app

Step 21. In the Outcome form pane on the right-hand side, click + Add form. 
Note: + New Form 
Note: The Manager form is already present in the right hand Properties pane. 

![image](https://user-images.githubusercontent.com/1082625/219224228-0d9b6a13-b6b2-447b-8431-99957fece30b.png)

=======================
Task 10.2 – Environmental Project Delivery app
Note: Same issue as 10.1
=======================

**Comment by bpmoring** [comment]
Requested changes made.

**Comment by shrutishaw07** [comment]
I had the same doubt for exercise 10.1 and 10.2 ......where are the changes made can you provide me the link !!
