### ISSUE TITLE
Practice Lab 3.2 – Views

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#175]
Exercise 7 – Modify model-driven apps
Step 10 - Add the following views:

Active Projects
Completed Projects
My Active Projects

Note: These views already seem to be part of the add! 
Note: There is no + Add View but rather + New View. 

![image](https://user-images.githubusercontent.com/1082625/219231425-26046d7b-fcaf-48b4-a055-e22d5abe66aa.png)

Step 14: Add the following views:

Active Milestones
Inactive Milestones
My Pending Milestones

Note: Same issue. 

Step 18: Add the following views:

Active Outcomes
Inactive Outcomes

Note: Same Issue

=================================

**Comment by bpmoring** [comment]
Changed wording to + New view.
