### ISSUE TITLE
Practice Lab 4.1 – Build a canvas app

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#176]
Some students really struggled with this lab. Two of them have never built a Canvas app but even the ones that had found it hard. And that was after I briefed them on the lab "gotya areas" and other fine points to watch out for in advance. For example, I was sure to demonstrate that the Properties panel has several tabs and that some of the properties they would be looking for are on the Properties tab while others are on the Advanced tab as the lab is not clear on that. The lab took a full two hours and that required a lot of helping them find what they were looking for or to confirm what they were doing was correct. I only had six students and can't imagine what it would be like with a class of 24! 

There are a few mistakes in the lab or areas where much better clarification is needed.

**Comment by bpmoring** [comment]
Thank you for this feedback. We will keep this in mind for future lab development.
