### ISSUE TITLE
Week of Feb 13 run of PL-200 - Notes to the Content Owner 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#177]
Note: Once the content team has reviewed this issue please close it. 

Hello Content Team

I believe I am one of the early MCTs to deliver the new revision of the PL-200. It's quite an update. Please review the other Issues I have opened thus far. 

I went through labs 5 through 7 this evening prior to the last day of the course. I was able to complete them without major issues. I will give the people that created the labs full credit for the technical depth of the labs. The way the lab instructions have been written and, given the ongoing evolution of the portal UIs, they will indeed be a challenge to many students that attend the course. In reading the trainer handbook that would appear to be the goal of the lab creators and I would suggest that the goal has been accomplished.

It is very clear that those attending the course that have not done the PL-900 and the PL-100 at a minimum will really struggle in this course. And given the labs have to be completed in sequential order the odds of those that do not meet the prerequisites completing all of the labs successfully in the right order will also be a challenge, not only for the Instructor but for every other student in the classroom because of the delays in helping a few of them be able to move forward. There are no quick recovery options provided in the course given the nature of the cloud is a live environment, even though this can be achieved, that would allow the Instructor to help a student get beyond a lab they could not complete. The Instructor can only troubleshoot these issues before having to move on in order to keep the course moving forward. 

I had to help a student who could not complete lab 1.6 and after troubleshooting their implementation for 15 minutes without resolution we had to move on. To do so, I had to export my completed solution, email it from my Office tenant admin account to my personal account because I could not email it to the student's admin account directly because the email was blocked, upload the zip file from the email to Onedrive and provide the shared link, then shadow the student's VM to have the student open the Onedrive link, download the Solution zip file and import it into their environment. It took 30 minutes to help one student get back on track while others waited.   

Suggestions: 

1. Provide Start Point Solution Zip files for each module so that the Instructor can easily get a student back on track when, for whatever reason, their lab attempt failed. 
2. Provide better clarity in the instructions. 
3. Include screenshots because this is the only way people who have very little experience are going to get through the labs in the time allocated. I know that it is very hard to do but it does make the course more accessible and inclusive. 

It is a great first version of the new labs. Hopefully, other MCTs will chime in over the next month and the early course delivery experiences can be quickly incorporated so that the course is more inclusive of the reality of the range of students we have in participating in the classroom. 

Thank you again to the PL-200 team. Keep up the great work and I look forward to future updates to the course. 

Sincerely; 

AV

**Comment by bpmoring** [comment]
Thank you @arnoldvilleneuve we are working through the items identified and will submit an update in April.

**Comment by arnoldvilleneuve** [comment]
What about all the Instructors that have to teach it between now and then.Get Outlook for Android

**Comment by bpmoring** [comment]
Some of the issues can be addressed before the April timeline. The adding of images is a larger pull and would need the additional time. We will go through and identify the issues that require less time and address those first. Thanks again for your feedback.
