### ISSUE TITLE
Practice Lab 6.1 – Cloud flows

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#178]
Task 1.4 – Set status to rejected

In Dynamic content, search for outcome and select Outcome under the Get Outcome section.

1. Expand Show advanced options.

2. Select No for Approved.

3. Select Rejected for Status Reason.

4. Click Save

Note Popup that "This isn't the latest content". 

Workaround

We selected "Overwrite other peoples changes" to move forward. 

![image](https://user-images.githubusercontent.com/1082625/219732328-12f0aa03-a008-47f7-ab63-76b384477ed1.png)

**Comment by bpmoring** [comment]
Added note stating the workaround.
