### ISSUE TITLE
Exercise 2 lab 0 should be asfter lab 1.1

### ISSUE THREAD

**Issue by Yash-malhi** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#179]
# Module: 00
#### Step: 00

Description of issue:
Hi team,

Under lab 0: to validate the lab environment exercise 2 asks us to create a portal that will take an hour to deploy.

Now one of the steps in the exercise asks us to switch to the practice environment. Experienced users know that they need to create the environment first.
But for the inexperienced the lab instructions are in Lab 1.1 teaching how to create the practice environment.
Request you to sort the order.

Thanks.

Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
Combining with issue #167
