### ISSUE TITLE
DataMigrationUtility.exe doesn't work

### ISSUE THREAD

**Issue by Watana1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#180]
# Module: 01
#### Step: 03

Description of issue
DataMigrationUtility.exe doesn't work.

https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/blob/master/Allfiles/Labs/ConfigurationMigration/

**Comment by julians1966** [comment]
I have tested this and the Configuration Migration Tool runs in an ALH environment.

**Comment by bpmoring** [comment]
Closing due to inability to replicate.

**Comment by TuPham1202** [comment]
I has double-click on DataMigrationUtility.exe but it not work. Anyone help me

**Comment by julians1966** [comment]
First raise a new issue and not update a closed one
Are you using a lab environment provided by an Authorized Lab Hoster? If so which one?

Workaround
Download and install the Power Platform CLI https://aka.ms/PowerAppsCLI
Then use the command pac tool cmt
