### ISSUE TITLE
Open Issues?

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#181]
Hello 

I have a PL-200 scheduled to run in two weeks. The issues below have been on the docket for attention for over five weeks now. Is there a projected date for them to be resolved? 

Arnold

**Comment by bpmoring** [comment]
Hi @arnoldvilleneuve, there will be an update to the labs at the end of March. This should address most of the issues identified. Thanks!
