### ISSUE TITLE
Developer Plan no longer works 

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#183]
# Module: 01
#### Step: All

Description of issue: Developer Plan no longer works

Repro steps:

1. https://powerapps.microsoft.com/developerplan
1. Existing user? Add a dev environment
1. Error: You need a Power Apps license to use this app

**Comment by julians1966** [comment]
I have created a PR to use the Developer environment type in the Power Platform Admin Center

**Comment by bpmoring** [comment]
Implemented the Pull Request. Thank you.
