### ISSUE TITLE
Purchase services removed from admin center - unable to add a trial

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#184]
# Module: 00
##### Step: 7

Description of issue

Purchase services not available in Microsoft 365 admin center so cannot start a trial

![Purchase services missing](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/29278645/12f33519-9a26-4bea-9a0b-7141ad968a81)

**Comment by julians1966** [comment]
Workaround

1. Navigate to https://powerapps.microsoft.com/ and click Start free.
2. Under Work email, enter Microsoft 365 email address for the lab in the text box below Enter your email to start your free trial, check the agreement box, and click Start your free trial.
3. Enter the Microsoft 365 password for the lab if prompted and click Sign in.
4. Select Yes to stay signed in?
5. Enter 1234567890 into the Phone Number field.
6. Navigate to https://admin.microsoft.com/.

Note: When adding licenses use Power Apps Plan 2 Trial instead of Power Apps per user plan

**Comment by ephiax20** [comment]
Hi @julians1966 I am unable to replicate this using the Skillable VM/ provided M365 tenant.  Please can you give any more details about your environment or set up for running the Lab?

The workaround makes sense, a lot of other PL courses use these steps instead.

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/9944cc3a-477e-4665-a2cf-73fad78b708f)

-Simon

**Comment by julians1966** [comment]
See https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/issues/78 for more details

**Comment by julians1966** [comment]
I am teaching PL-400 this week for another lab hoster and all student tenants have had this problem

**Comment by ephiax20** [comment]
Thanks, I'm trying to investigate this but it is more likely that the workaround steps will be incorporated into the Instructions, PL-500 has similar steps in the environment set up labs.
