### ISSUE TITLE
Plan 2 not available in Power Apps Licenses when configuring Power Platform Trial

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#187]
### Step: 04 - Check the box for Power Apps Plan 2 Trial.

Description of issue

The manual instructs to add PowerApps license "Power Apps Plan 2 Trial", but there is no such option for power apps under "licenses and apps". There is a plan and a plan 3, but no plan 2 available [p1].

[p1]

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/94069201/1385f1d5-f498-4d97-b095-638ced966043)

**Comment by ephiax20** [comment]
Unable to replicate. It looks fine for me using Lab Profile 42217

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/637d6ebc-848b-4060-beea-7246a557afd9)

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/74e474b4-1037-475c-8fab-6a49dfebe37a)

**Comment by julians1966** [comment]
This issue seems to be specific to individual tenants. Some tenants still have the Power Apps Plan 2 trial whereas others are Power Apps Premium or Power Apps for Developers.

**Comment by julians1966** [comment]
See this tenant I am currently using for PL-400

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/29278645/4bd36ae2-8fbc-468e-a49e-28410a9d3264)

**Comment by julians1966** [comment]
ID	33147834
Host	EU-HV12
Datacenter	EU North (London)

**Comment by ephiax20** [comment]
Thanks.

Workaround: Select **Plan 3**.

Maybe we could just update the instructions to say "an appropriate Power Apps license" or is that too vague?

**Comment by MTawfik86** [comment]
Hello Simon,

Thank you for your support.

This is about PL 200 (not PL 400)

This is the tenant:
M365x39225156.onmicrosoft.com

Username:
                ***@***.******@***.***>


I am not able to see these plans:
***@***.***

Thanks,


Mohamed Tawfik
Microsoft Senior Cloud Solutions Architect- CoE Europe

***@***.***

TD SYNNEX
C/ Acer 30-32, 08038 Barcelona
(+34) 651-192538
(+34) xxx-xxxx
***@***.***

**Comment by ephiax20** [comment]
Thanks Mohamed, appreciate your assistance. This issue seems to be tenant specific, not course specific.

**Comment by MTawfik86** [comment]
Thanks Simon,

Me and the lab provider see the same. So it seems that the course is not stable.

I am testing it because I have scheduled class with participants from all Europe

Best Regards,
Mohamed

**Comment by julians1966** [comment]
It's not the course, Microsoft has recently changed the license plans for Power Apps and Power Automate and is rolling these changes out over the different tenants around the world. The Power Apps Plan 2 Trial license has been replaced by Power Apps Premium Trial or Power Apps for Developer depending on where you create the license from. 
If you follow the instructions in Lab 0 in PL-200 labs, you will either end up with a Power Apps Plan 2 or a Power Apps for Developer license. Choose whichever one is available
Note: Documentation has not been updated to match these changes yet

**Comment by MTawfik86** [comment]
Ok thanks Julian,

I guess the course should be updated then.

Its very hard within a class to decide to whom we point, Microsoft, the course content, the lab provider, or the student account.

Thanks again.
Best regards,
Mohamed

**Comment by julians1966** [comment]
If you are teaching Power Platform then you need to get used to this, Microsoft is always changing something which affects lab steps.
Be aware that when running a course, students each have their own tenant and some tenants will be the old version and some tenants may have been updated!
It is not possible to simply update the lab steps for the latest changes as not everyone will see those changes.
