### ISSUE TITLE
Lab 3.1, Exercise 10 - Portal Interface changed

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#192]
# Module: 03
### Exercise 10, both Exercise 10.1 and 10.2

Description of issue:
It seems that the Portal has changed, and the instructions no longer match.   For example, Exercise 10.1:

- Steps 1-18 you add some 2 tables.  That works fine.

- Step 19 and 20 say "Expand Outcome in the Pages pane on the left-hand side."   However, it's not called "Outcome" any more, I think you click on "Outcome forms" under the "All other pages" section.  

- Then in steps 21-22, you add the Manager form; however, it already shows that both the Manager form and the User form are already added to the app.

Task 10.2 is similar, except it's the Environmental Project Delivery app, but the instructions have the same issue as Task 10.2

Same issue in Lab 3.2, Exercise 7... The instructions are to edit the Environmental Project Delivery app and add some views, but all the views are already there...  Not sure if some of them should actually be removed or not!

**Comment by ephiax20** [comment]
Replicated and reproduced the analysis.  Pending removal of these tasks, will need to get this confirmed. Thanks for logging.

**Comment by ephiax20** [comment]
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/fefacbcf-fd84-4788-9035-8aa801e542f8)

**Comment by julians1966** [comment]
All forms are automatically included in the app. Task 10.1 is to remove the other form, leaving only the Manager form in the Environmental Management app. Task 10.2 is to only leave the User form in the Environmental Management app, so each app uses the appropriate form

**Comment by julians1966** [comment]
Again, in Lab 3.2 all public views are automatically included in a model-driven app and the task is to select only the view to include and to exclude the others

**Comment by julians1966** [comment]
Views are not controlled by security roles and it is an important skill to know how to exclude views from an app
