### ISSUE TITLE
Table permissions incorrect for Power Pages

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#200]
# Module: 5
#### Step: 14

Unable to edit milestones in the Power Pages site

The table permissions for the Project table should be Append not Append To

**Comment by ephiax20** [comment]
Hi @julians1966  I think Append and Append To would be better here, as the Project table can be related back to Programs and Project Resources, Milestones, Outcomes etc. can be related to Projects ?

The data model is here: https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BPL-200%5D_M01L04_Tables.md#scenario

**Comment by julians1966** [comment]
But only Projects and Milestones have been added to the Pages site, so the minimum necessary security is Append
