### ISSUE TITLE
Lab 2.3 - Cannot export data

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#207]
# Lab 2.3
## Exercise 1

I'm not 100% if this is my mistake...  :)    

Exercise 1 has you export data from the Project table.   However, when you do the export, an error pops up:
"Connection to dataverse failed.  Please check the link below on how to fix this issue."

When I click the link to investigate, it takes me to https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-import-export#troubleshoot-connection-issues   when says "Get Data from Excel and Export Data features are currently not included in the Power Apps Developer Plan."   But that is the type of plan we use in these labs.

So I'm not sure if it's my issue, or the lab needs to be changed, or delete this exercise.

**Comment by tylerfarmer1** [comment]
Thanks Julian.  Is there an ETA on that next major update?

**Comment by julians1966** [comment]
Due January 2024 but will likely need to update this lab beforehand

**Comment by tylerfarmer1** [comment]
If I can help with beta courses, I'd be happy to, been teaching the PL-900, 100, 200, 400 and 500 for a year now.

**Comment by ios-x** [comment]
The export option fails everywhere not just in the lab, so i think its a general issue

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
