### ISSUE TITLE
LAB[PL-200]_M04L01\Exercise_4\Task_4.1\Step15

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#208]
# Module: 04
#### Step: 15

In Dynamic content, the **Ask in PowerApps** option is not available.

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/133017642/15e93a68-ab2a-454c-962c-674160f6d945)

**Comment by julians1966** [comment]
Addressed by PR #205

**Comment by J0eGos** [comment]
I am unable to see where this is addressed in PR #205, is it possible to get some better clarity on this? I see changes to the prior steps but the step asking you to select "Ask in Powerapps" is still present

**Comment by julians1966** [comment]
You are correct, it needs to do more. When that PR is merged, I will make further changes to remove the Ask in Power Apps step

**Comment by Nimra-Maryam** [comment]
Any Update?

**Comment by julians1966** [comment]
Resolved by #219

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
