### ISSUE TITLE
# Module: 05 An infinite loop is created in the approval workflow.

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#21]
# Module: 05
## Lab:5.6
###Exe 2
####Task: 08
##### Step: 06

Description of issue
An infinite loop is created in the approval workflow.
Repro steps:

1.Folllow Lab as is to reproduce.

## Lab:5.6
###Exe 2
####Task: 08
##### Step: 06 

Locate the Approval Status Value field and select Approved. **UPDATE Notify Manager column to NO**

**Comment by guthubcloudittogether** [comment]
drop me an email at cloudittogether@gmail.com

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by DanePillay-nel** [comment]
I have delivered the course after the incident was reported and it was resolved. Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
