### ISSUE TITLE
LAB[PL-200]_M05L01\Task 1.3

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#210]
# Module: 05
#### Step: 04

The **Portal Management** app is not available.

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/133017642/727bff6b-ddbd-4033-b6df-8fe37f4d5ab2)

**Comment by julians1966** [comment]
Portals is now Power Pages

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
