### ISSUE TITLE
Lab 5.1 / task 2.3 / step 26 - unclear of lab intentions as i dont see the mention of "data"

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#212]
# Lab 5.1 power pages
#### Step: 26

Description of issue
I am seeking clarification of this step please - as i dont see the mention of "data".

To be honest, i think Practice lab 5.1 needs a little update to clarify some steps as we go, as the wording the pages isn;t always clear. could someone please retest this start to finish?

Repro steps:
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/89986870/3bd24803-ff3b-4b31-bc68-8593a274d1db)
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/89986870/e1907fa8-4abd-407c-80f0-8e261abc18e2)

**Comment by julians1966** [comment]
Under Set up there used to be a tab called Data
It was renamed to Actions  - see https://learn.microsoft.com/en-us/power-pages/getting-started/add-list
But the Actions tab has now disappeared - I have verified this today - this looks like a product issue not a lab steps issue

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
