### ISSUE TITLE
LAB[PL-200]_M05L01_Pages\Task 1.3\Steps 4 and 7

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#214]
# Module: 05
### Step: 04 and Step 07

The UI does not include Portal Management. When executing the steps with Power Pages Management, the MOD administrator contact is not there upon selecting Contacts in Step 07.

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/133017642/76990559-f222-42d6-aac9-bd8a7d76d477)

**Comment by julians1966** [comment]
See Issue #210

**Comment by julians1966** [comment]
You need to sign into the portal using Azure AD as MOD Administrator for the portal contact to be created
