### ISSUE TITLE
Lab 1.1 - minor issue with adding dataverse

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#215]
# Lab/Demo: 1.1 - Create Environments
#### Step: 7

Description of issue
Step 7 says "Toggle the Add a Dataverse data store to Yes."     (actually Dataverse is mis-spelled)

I believe you can just remove this step.  When you create an environment that is type "Developer" then the option to add a Dataverse is already turned on, and it's disabled (you can't turn it off).

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
