### ISSUE TITLE
Lab 1.2 - update instructions due to UI change

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#216]
# Lab/Demo: 1.2 - Publisher and Solution
### Task 1.2 - Create a publisher

In Step #2 the instructions tell you to pick the Publishers tab at the top; however, Publishers have moved.  I have my students click the "...More" link in the left navigation, then click the "Discover All button.   Next use CTRL+F (or scroll down) to find Publishers and click the "pin" so that Publishers are included in the navigation.   Then you can start on Step #3 to add a new Publisher.

**Comment by julians1966** [comment]
Resolved by #219

**Comment by chandlersyal** [comment]
Please see updated labs merged today! Thanks.
