### ISSUE TITLE
Lab 1.3 - Minor step correction

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#218]
# Lab 1.3 - Import Solution
#### Step: 2

Description of issue:
Step 2 says:
Make sure you are in your **[my initial] Development** environment.

It should say:
Make sure you are in your **Dev One** environment.

Also #### Step: 16
It says:
Select **Import.**

It should say:
Select **Next**, and then select **Import.**

**Comment by ephiax20** [comment]
Hi Tyler, there's currently some issues being investigated and remediated on **Dev One** so this is a workaround to use the old instructions for the time being.  It is currently anticipated that these issues *should* be resolved by early next week. Thanks for your understanding. - Simon
