### ISSUE TITLE
Strange behavior with lab hoster?

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#220]
I know the labs were just refreshed on Jan. 19th.   Today is Jan. 20th, so this might just be a timing issue...

I'm running through the labs with our lab hoster (Labondemand.com).   As you progress through the labs, from Lab 1.1 to Lab 1.2, etc., everything seems to be working smoothly.    

It breaks after Lab 1.6.  When you click "Next" to go the next lab (which should be Lab 2.1) the page give the "Congratulations!  you have successfully completed this exercise. Click Next to advance to the next lab."   If you click the "Next" button 7-8 times, you eventually end up at Lab 3.1.

Then after Lab 3.2 you get the "Congratulations" page with no instructions again.   And it happens again after Lab 6.1

**Comment by julians1966** [comment]
This looks like a lab hoster issue as some labs have been removed and some renumbered and I guess they need to update their lab environment. So I would raise with Skillable.

**Comment by chandlersyal** [comment]
@tylerfarmer1 I have reached out to Skillable to see how we can get this fixed. Thank you for raising!

**Comment by chandlersyal** [comment]
closing per Skillable's response. They have validated on their end.

**Comment by tylerfarmer1** [comment]
Thank you everything looks great now!

Tyler Farmer
***@***.******@***.***>
602-326-1042
