### ISSUE TITLE
Lab 1.3 - number issues?

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#221]
# Lab/Demo: 1.3 - Import Solution
### Task: 1.1 - Main Solution

I'm not sure if this is a GitHub issue or the Lab Hoster issue.   It is referring to the Step Numbers.

In Task 1.1 there are 20 steps.   When I look at the instructions using this URL, it shows all 20 steps numbered correctly:
[https://microsoftlearning.github.io/PL-200-Power-Platform-Functional-Consultant/Instructions/Labs/LAB%5BPL-200%5D_M01L03_ImportSolution.html](Link)

In the Lab Hoster, it shows Steps 1-5.   Then there is a "note" and an "image"...and right after the image it starts with Step 1 again instead of Step 6.

Then at Step 12 (which is should be step 17), there is another picture, and the Steps start numbering at 1 again (which should be Step 18).

See 2 attached pictures for exampls.

I see this is several Labs/Exercises;  I can document them here when I see them if you'd like...but again, I don't know if this is GitHub / Markdown issue, or if it's on the lab hoster side.

![s1](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/72703514/7f262818-84c4-44c7-843b-1841b1968b70)

![s2](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/72703514/664434a0-2d15-4087-b140-ee841e132eb5)

**Comment by julians1966** [comment]
The markdown in the lab files is correct, but I have seen this before in the lab environments and may need to adjust the indentation of the images for them to appear correctly.
I have checked the other lab providers to see if they have the same issue but none of them have yet updated their labs.

**Comment by chandlersyal** [comment]
@tylerfarmer1 which Lab Hoster are you using?

**Comment by chandlersyal** [comment]
@tylerfarmer1 I have reached out to Skillable to see how we can get this fixed. Thank you for raising!

**Comment by julians1966** [comment]
@tylerfarmer1 @chandlersyal  Godeploy have updated their lab environment over the weekend and the images and numbering appear correctly
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/29278645/1fe9dd1f-4333-476a-8598-5aaf8de72726)
So this is an issue for Skillable

**Comment by julians1966** [comment]
See also this which is correctly numbered

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/29278645/7be31aad-92bb-45f7-9fd1-11d99e271a61)

**Comment by tylerfarmer1** [comment]
Thanks, I will raise a ticket with them, I'm teaching this course this week.

Tyler Farmer
***@***.******@***.***>
602-326-1042

**Comment by chandlersyal** [comment]
Merged the above PR that resolves this issue. Thanks!
