### ISSUE TITLE
Lab 4.2 Create a custom page - Steps not matching power apps portal

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#231]
#### Step: 7

Description of issue
The steps state to do the following: 

1. Navigate to the Power Apps Maker portal https://make.powerapps.com/.
2. Make sure you are in the Dev One environment.
3. Select Solutions.
4. Open the Fabrikam Environmental solution.
5. In the Objects pane on the left, select Apps.
6. Select the + New drop-down and select App then Page.
7. Select With layout and select Split Screen.

However, when you add a new **App > Page**, you are not prompted with any "with layout" or "split screen* option, neither is this option on the screen which follows. Steps need correcting.

**Comment by julians1966** [comment]
This is what you see after step 6
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/29278645/bf56cbfa-92af-4111-8b09-057486536c0a)

**Comment by LewisGoDeploy** [comment]
My apologies! You are right. This wasn't appearing very clearly for me initially. Thanks for the quick response
