### ISSUE TITLE
Invalid URL for Maker Portal

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#232]
# Module: 1
#### Step: 8

Description of issue

URL is incorrect - lab step is **https://make.powerapps.com/environments** it should be **https://make.powerapps.com**

Repro steps:

1. Navigate to https://make.powerapps.com/environments

**Comment by ephiax20** [comment]
Is this GoDeploy specific too?   It looks correct on Skillable, as far as I can tell.

**Comment by julians1966** [comment]
Yes, looks like GoDeploy have not picked up the latest PRs
I will raise with them
