### ISSUE TITLE
Files missing from VM

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#234]
# Module: 1
#### Step: 5

Description of issue

There are no files in Documents\PL-200 or even a PL-200 folder in the VM

Need instructions/steps to download the files from GitHub

**Comment by ephiax20** [comment]
I am confused, are you definitely looking at the correct Instructions here @julians1966 ??

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/6cc1b93a-fdd4-4edb-8123-60c597606a16)

The button to download the Lab files is on the very first page of instructions, before the GitHub instructions.

**Comment by julians1966** [comment]
Files are missing on Godeploy 
Files are not missing on Skillable

Reported issue to GoDeploy

**Comment by julians1966** [comment]
GoDeploy have added PowerShell to download the files
