### ISSUE TITLE
Practice Lab 3.3 command bar - patch formula has invalid arguments

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#236]
# Module: 3
#### Task  1.1 / Step 12

Description of issue - I have followed the instructions to enter the formula, however i have an error message on the formula (it doesn;t seem to recognise project outcomes as the source - please advise on the fix.

Repro steps:
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/89986870/85233503-fe33-4558-bec0-9e913d695b07)

**Comment by ephiax20** [comment]
The steps to add the **Outcome Completed Date** column are in Lab 1.5 - Columns, Exercise 5, Task 5.1 Steps 11-14. https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BPL-200%5D_M01L05_Columns.md#:~:text=Enter%20Outcome%20Completed%20Date%20for%20Display%20name

The Project Outcomes table should be created in Lab 1.4 Tables, Exercise 3, Task 3.1

This course is designed to completed in order, so each lab is a prerequisite to the next.
