### ISSUE TITLE
Lab 4.2 - Create a custom page - task 2.4 no page showing to select

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#237]
# Module: 04
#### Step: 12

Description of issue
I cannot see the project resource page, even though it was created and published.

Repro steps:
![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/89986870/11f119dc-6391-4747-bb86-99f7fa2ce8b0)

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/89986870/c36790ed-363f-4a8c-8313-57ae01a6abb1)

**Comment by ephiax20** [comment]
Unable to replicate this issue.

The page is showing as expected, for me.

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/116392278/4f1d597a-03cf-4f91-9c7c-4eca939034f4)
