### ISSUE TITLE
Possible UI change 

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#24]
## Lab/Demo: 2.2
##Exercise: 01
#### Step: 07,08

Description of issue
Allow feedback checkbox appears to have moved. There is an option at the bottom of the pane titled Can be linked to feedback. Is this the same thing?

![image](https://user-images.githubusercontent.com/72228536/143938884-08973442-b7f6-41f6-9034-d4bb512322be.png)

**Comment by chandlersyal** [comment]
Thanks!
