### ISSUE TITLE
Adding editable grid doesn't work

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#240]
# Module: 03
### Task: 6.1

It seems adding Power Apps grid control is somehow broken. When following steps, the "Done" button never comes available. It might be a bug, since the button activates when Child Items (preview) is selected. The same is true for editable grid component

![image](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/62485576/88aa024d-aa01-45fc-85d5-91f7cd20755a)

Repro steps:

Follow lab guidance

**Comment by chandlersyal** [comment]
Hmmm. Are you still able to reproduce this? I am not, so I think it might have been a one-off bug? Please let me know if you are still experiencing this.

**Comment by ArturoBravo111** [comment]
We are also experiencing the same issue, any updates please?

![Screenshot 2024-05-21 144311](https://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant/assets/34762894/35a46237-a6c0-4296-972e-8ecb66a166e9)

**Comment by chandlersyal** [comment]
I am working on validating this and will update as soon as I can. Thank you for following up!

**Comment by julians1966** [comment]
Confirmed that this issue is still present.
This feels like a bug in the control with the preview of child items

**Comment by a-ainamdar** [comment]
I can confirm that this issue is not reproducible. Done button is not greyed out.
Refer image below
![image](https://github.com/user-attachments/assets/f10d3bfa-6038-4d4b-9d2b-75ad136f47b1)

**Comment by chandlersyal** [comment]
Closing as not reproducible. Thanks!
