### ISSUE TITLE
steps mismatched with screenshot

### ISSUE THREAD

**Issue by saquibshera** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#245]
# Module: 1
## Lab/Demo: 1.2
Exercise 1
#### Step: 04

Description of issue
They told to select the Devone environment but in screenshot display pl-development...Please fix 
Repro steps:

1.
1.
1.

**Comment by saquibshera** [comment]
![Uploading Screenshot 2024-09-17 at 9.36.40 AM.png…]()

**Comment by a-ainamdar** [comment]
Thank you for raising this. We will update this screenshot soon

**Comment by miberr** [comment]
@a-ainamdar I'm delivering this course rn and already fixed this in my fork. Ill send a pull request tomorrow 😊
