### ISSUE TITLE
Conflicting instructions for lab 4.1

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#246]
#### Step: 13

No new row can be added. This is because in lab 1.5 project status field was marked as required and it is not given in the patch call. 

![image](https://github.com/user-attachments/assets/2d5ef890-1280-4352-847f-ec9782d5945d)

Field was marked as business required in lab 1.5, task 1.1 step 13

Repro steps:

Follow lab guidance

**Comment by julians1966** [comment]
Changed the formula in the canvas app to 
Patch(Projects, Defaults(Projects), { 'Project Title':"New Project", 'Project Status': 'Project Status'.Planned})
