### ISSUE TITLE
Datataverse Low Code plugins not working

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#247]
### Task: 2.1

Datataverse Low Code plugins not working. The editor claims that `ThisRecord` is not recognized. This in turn causes that the plug-in cannot be saved. I'm quessing theres a bud in Dataverse Accelerator App... Maybe this exercise should be removed until the app reaches ga?

![image](https://github.com/user-attachments/assets/b2bc2aa3-8f81-4d9f-b730-3bc6269b1450)

Repro steps: follow lab guidance.

**Comment by julians1966** [comment]
It's a change in Power Fx
Use NewRecord instead of ThisRecord

**Comment by miberr** [comment]
🤦🏻‍♂️ Of course it is... Thanks for letting me know 👌🏻 The documentation needs refreshing as well.
