### ISSUE TITLE
Lab 4.2 Task 4 Remove Rating and Source Column

### ISSUE THREAD

**Issue by AnugerahSS** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#59]
# Module: 04
#### Step: 00

Description of issue

I experienced error if I fill the Rating and Source Column in the Feedback Form.

Is it not better to remove the Rating and Source Column in the Feedback Form?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has resolved this issue with pull request #65
