### ISSUE TITLE
ALL LABS M07 are not related to Power BI, but are titled "Analyze data with Power BI" 

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#6]
# Module: 07
## Lab/Demo: 07/ALL

Description of issue

Why ALL LABS 07 (LAB[PL-200]_M07L01 through LAB[PL-200]_M07L06) are "titled" **Analyze data with Power BI** when none of this lab is related to Power BI?

For example, according with Skillpipe manual:
**LAB[PL-200]_M07L02_Word_template.md** is related to Module 3 Work with the Dataverse > Use tabular reporting options > Use Word templates
**LAB[PL-200]_M07L03_Excel_template.md** is related to Module 3 Work with the Dataverse > Use tabular reporting options > Use Excel templates
...
**LAB[PL-200]_M07L06_Export_data.md** is related to Module 3 Work with the Dataverse > Import and export data > Export data

**Comment by chandlersyal** [comment]
These labs do belong under the PBI module, officially, but will possibly move in future update.
