### ISSUE TITLE
Lab 12.5 Missing data in Pivot Table and Charts

### ISSUE THREAD

**Issue by ChRocheFR** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#60]
# Module: 12
#### Step: 11

Description of issue
Before adding the Chart, seems useful to select data for the Pivot Table first, in order to see something. For instance, user can select in PivotTable Fields pane, the Knowledge Assessment, Owner and Total Points fields.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue
