### ISSUE TITLE
Lab 10 - Chat Bots - Authoring Canvas Option needs to be removed

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#66]
# Module: 10
## Lab: 10
##Exercise: 3
#### Step: 02

Description of issue
The UI has been updated. You now select a topic which takes you straight to the authoring canvas. Here, you enter the trigger phrases and then close the window down. Any references saying select Authoring canvas needs to be removed and the steps shortened.

Repro steps:

1.
1.
1.

**Comment by ios-x** [comment]
true

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull requests #76, #77, #78, #79, #80, and #81.
