### ISSUE TITLE
Lab 4.2: Practice Lab – Work with data and services

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#67]
# Module: 04
#### Step: 05

Description of issue
I am certain this use to exist, but its not there any longer.
When you ask the users to add formulas to the Onstart property, step 5, you forget to say, select the app section and select RUN ON START. Without this the onstart formulas won't run. So this needs 
![labissuepl-2001](https://user-images.githubusercontent.com/59872097/164426760-5c16475e-057c-4525-b781-af3b6236e51d.JPG)
adding back in
Repro steps:

1.
1.
![labissuepl-2001](https://user-images.githubusercontent.com/59872097/164426891-11c90447-9780-410b-a0ae-315b87709e89.JPG)
![labissuepl-2002](https://user-images.githubusercontent.com/59872097/164427046-517b5a8e-02f9-4ebb-b10b-9a71b6898652.JPG)

1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
