### ISSUE TITLE
Dataverse terms

### ISSUE THREAD

**Issue by fawcettm** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#7]
# Module: 03
#### Step: 10

Description of issue 
Lab Instructions refering to entities, fields, option sets need to be updated to tables, columns and choice / choices respectively.

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
Reviewing all content soon to ensure it is up to date. Previous merge should have caught all of these.
