### ISSUE TITLE
Dataverse naming update

### ISSUE THREAD

**Issue by fawcettm** [MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant#8]
# Module: 3, 4
#### Step: 04

Description of issue  Need to change terms for Dataverse:
Entity to Table
Field to Column
Option Set to Choice / Choices

Apologies, too many lines to detail!

**Comment by chandlersyal** [comment]
Reviewing all content soon to ensure it is up to date. Previous merge should have caught all of these.
